# Copyright 2026 JimVulkan
# SPDX-License-Identifier: MIT
"""panvk_bc_tables_gen.py -- the lookup tables of bc_decoder.glsl as one C array, in the member
order of its BcTables storage-buffer block (compiled in with -DBC_TABLES_BUFFER).

PanVK has no constant-data path: a constant array a shader indexes dynamically is copied to every
thread's stack, 10 KB per thread for the BC7 -> ASTC transcoder. So PanVK's variants read the
tables from a buffer the driver fills with this array, taken from the same source as RADV's
constant arrays, so the two cannot drift apart.

   panvk_bc_tables_gen.py <bc_decoder.glsl> <out.h>
"""
import re
import sys

src = open(sys.argv[1], encoding='utf-8').read()

# The BcTables block, in order: the member list IS the layout (std430, 4-byte elements).
block = re.search(r'readonly buffer BcTables \{(.*?)\};', src, re.S)
assert block, 'no BcTables block in the shader'
members = re.findall(r'(uint|int)\s+(\w+)\[(\d+)\];', block.group(1))
assert members, 'empty BcTables block'

words = []
names = []
for ty, name, n in members:
    n = int(n)
    m = re.search(r'const\s+%s\s+%s\[%d\]\s*=\s*%s\[\d*\]\((.*?)\);' % (ty, name, n, ty), src, re.S)
    assert m, 'no constant definition of %s[%d]' % (name, n)
    vals = [v.strip() for v in re.sub(r'/\*.*?\*/', '', m.group(1), flags=re.S).split(',') if v.strip()]
    assert len(vals) == n, '%s: %d values for [%d]' % (name, len(vals), n)
    for v in vals:
        x = int(v.rstrip('uU'), 0)
        words.append(x & 0xffffffff)
    names.append('%s[%d] at word %d' % (name, n, len(words) - n))

with open(sys.argv[2], 'w') as out:
    out.write('/* Generated by panvk_bc_tables_gen.py from bc_decoder.glsl -- do not edit.\n')
    for n in names:
        out.write(' *   %s\n' % n)
    out.write(' */\n#pragma once\n#include <stdint.h>\n\n')
    out.write('static const uint32_t panvk_bc_tables[%d] = {\n' % len(words))
    for i in range(0, len(words), 8):
        out.write('   ' + ', '.join('0x%08xu' % w for w in words[i:i + 8]) + ',\n')
    out.write('};\n')
